/*
 * Copyright (C) Petter H. Gustafsson
 *
 * This file is part of paparazzi
 *
 */
/**
 * @file "modules/findobstaclesfrommap/findobstaclesfrommap.c"
 * @author Petter H. Gustafsson
 * This module takes as input a file stored in the drone containing sonar data and gps data (alt, long, lat pos), finds
 */

#include "modules/findobstaclesfrommap/findobstaclesfrommap.h"

#ifndef FILE_PATH
#define FILE_PATH /data/ftp/internal_000
#endif

static FILE *mapdata = NULL;

// READ DATA FILE GENERATED BY DRONE
extern int file_reader(void)
{
	mapdata=fopen("map.csv", 'r');
    //fclose(mapdata);

  if (mapdata != NULL) {
    fprintf("data read");
  }
  return 0 ;
}

//-----------------------------------------------


//CREATE GRID BASED ON OBSTACLE ZONE
float DroneSafe=0.5;
int LongX=14; //cells in each direction
int LatX=14;  //cells in each direction
double gridpoints [LongX*LatX][2];

int k1=0;
int k2=0;
int k3=0;
int i;
int j;

for (i=1; i=LongX; i=i+1){
	b=i;
}


//for(j=1; j=LatX; j=j+1){
//gridpoints[1+k1*LatX:i*LatX, 1]=51.990601 + 0.0000043*k1;
//}
//k1=k1+1;

/**for i=1:LongX
    for j=1:LatX
        gridpoints(1 + k1*LatX: i*LatX,1)=51.990601 + 0.0000043*k1;
    end
    k1=k1+1;
end


for i=1:LongX
    for j=(1 + LatX*k2 ) : LatX*i
        gridpoints(j ,  2) = 4.376748 + 0.0000075*k3;
        k3=k3+1;
    end
    k3=0;
    k2=k2+1;
end
**/



void obstaclefinder
{



























}


